sudo: required
language: generic
services:
  - docker
before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t lena/docker-react-app -f Dockerfile.dev .
script:
  - docker run -e CI=ture lena/docker-react-app npm run test --

after_success:
  - echo "Test success"