version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    stdin_open: true
